apiVersion: v1
kind: Namespace
metadata:
  name: mlops
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-airflow-pvc
  namespace: mlops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-mlops-pvc
  namespace: mlops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
